#include <iostream>



int main(void)
{
	int arr[4] = {1,2,3,4};
	std::cout << arr[12] << std::endl;

	// try
	// {
	// }
	// catch(const std::exception& e)
	// {
	// 	std::cerr << e.what() << '\n';
	// }
	
	return 0;
}